--------------------------------------------------------
-- Archivo creado  - viernes-junio-08-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ELEMPRESTADOS
--------------------------------------------------------

  CREATE TABLE "SESAT"."ELEMPRESTADOS" 
   (	"USERID" NUMBER, 
	"ELEM" NUMBER, 
	"DATEIN" DATE, 
	"OBS" VARCHAR2(4000 BYTE), 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"GRUPO_INFORMACION" NUMBER, 
	"ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMACCIONINVESTIGACION
--------------------------------------------------------

  CREATE TABLE "SESAT"."FORMACCIONINVESTIGACION" 
   (	"ID" NUMBER, 
	"IDFORM" VARCHAR2(100 BYTE), 
	"TYPETIME" VARCHAR2(100 BYTE), 
	"PLANACCIONPREV" DATE, 
	"PLANACCIONRES" VARCHAR2(100 BYTE), 
	"PLANACCIONDATEEXE" DATE, 
	"PLANACCIONRECURSOS" VARCHAR2(100 BYTE), 
	"PLANACCIONRESCUMPLIR" VARCHAR2(100 BYTE), 
	"PLANACCIONDATECLOSE" DATE, 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"GRUPO_INFORMACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMINVESTIGACION
--------------------------------------------------------

  CREATE TABLE "SESAT"."FORMINVESTIGACION" 
   (	"ID" NUMBER, 
	"PREINFORME" VARCHAR2(200 BYTE), 
	"PERCENT" NUMBER, 
	"NITINS" VARCHAR2(100 BYTE), 
	"NITCON" VARCHAR2(100 BYTE), 
	"JEFAESTMAYOR" VARCHAR2(100 BYTE), 
	"UNITAC" VARCHAR2(100 BYTE), 
	"DIVCOMAN" VARCHAR2(100 BYTE), 
	"FUERZATAREA" VARCHAR2(100 BYTE), 
	"BRIGADADIRECCION" VARCHAR2(100 BYTE), 
	"CEDE" VARCHAR2(100 BYTE), 
	"DATENOVEDAD" VARCHAR2(100 BYTE), 
	"HORANOVEDAD" VARCHAR2(100 BYTE), 
	"MINNOVEDAD" VARCHAR2(100 BYTE), 
	"DATEANALISIS" VARCHAR2(100 BYTE), 
	"ZONANOVEDAD" VARCHAR2(100 BYTE), 
	"COORDIRECCION" VARCHAR2(100 BYTE), 
	"PAISNOVEDAD" VARCHAR2(100 BYTE), 
	"DEPNOVEDAD" VARCHAR2(100 BYTE), 
	"CIUDADNOVEDAD" VARCHAR2(100 BYTE), 
	"CARACLUGAR" VARCHAR2(100 BYTE), 
	"SITIOESPECIFICO" VARCHAR2(100 BYTE), 
	"CLASENOVEDAD" VARCHAR2(100 BYTE), 
	"NOVEDADINTERNAFUERZA" VARCHAR2(100 BYTE), 
	"NOVEDADINTERNAFUERZASUB" VARCHAR2(100 BYTE), 
	"GRAVEDAD" VARCHAR2(100 BYTE), 
	"PARTECUERPO" VARCHAR2(100 BYTE), 
	"PARTECUERPODES" VARCHAR2(100 BYTE), 
	"ATENCIONINMEDIATA" VARCHAR2(100 BYTE), 
	"INFOGRADO" VARCHAR2(100 BYTE), 
	"INFOCARGO" VARCHAR2(100 BYTE), 
	"INFONAME" VARCHAR2(100 BYTE), 
	"INFOEXTRELACION" VARCHAR2(100 BYTE), 
	"INFOEXTNAME" VARCHAR2(100 BYTE), 
	"FUENTEAGENTE" VARCHAR2(100 BYTE), 
	"AGENTE" VARCHAR2(100 BYTE), 
	"OTROAGENTE" VARCHAR2(100 BYTE), 
	"MECALESION" VARCHAR2(100 BYTE), 
	"NOMBREREPORTA" VARCHAR2(100 BYTE), 
	"GRADOREPORTA" VARCHAR2(100 BYTE), 
	"CARGOREPORTA" VARCHAR2(100 BYTE), 
	"PNOMBRE" VARCHAR2(100 BYTE), 
	"SNOMBRE" VARCHAR2(100 BYTE), 
	"PAPELLIDO" VARCHAR2(100 BYTE), 
	"SAPELLIDO" VARCHAR2(100 BYTE), 
	"PERSOGRADO" VARCHAR2(100 BYTE), 
	"PERSOCARGO" VARCHAR2(100 BYTE), 
	"ARMACUERPOESP" VARCHAR2(100 BYTE), 
	"PERSODOC" VARCHAR2(100 BYTE), 
	"DATEPERSONNAC" VARCHAR2(100 BYTE), 
	"LUGARPERSONNAC" VARCHAR2(100 BYTE), 
	"DATEPERSONINGRE" VARCHAR2(100 BYTE), 
	"PERSONCONTINGENTE" VARCHAR2(100 BYTE), 
	"TIMEPOSERVICIOANOS" VARCHAR2(100 BYTE), 
	"TIMEPOSERVICIOMESES" VARCHAR2(100 BYTE), 
	"TIMEPOSERVICIOANOSUNIDAD" VARCHAR2(100 BYTE), 
	"TIMEPOSERVICIOMESESUNIDAD" VARCHAR2(100 BYTE), 
	"HORASLABORADO" VARCHAR2(100 BYTE), 
	"MINLABORADO" VARCHAR2(100 BYTE), 
	"TIMEPOSERVICIOANOSCARGO" VARCHAR2(100 BYTE), 
	"TIMEPOSERVICIOMESESCARGO" VARCHAR2(100 BYTE), 
	"PERSONDIRECCION" VARCHAR2(100 BYTE), 
	"PERSONCIUDAD" VARCHAR2(100 BYTE), 
	"PERSONTEL" VARCHAR2(100 BYTE), 
	"PERSONEDAD" VARCHAR2(100 BYTE), 
	"PERSONSEXO" VARCHAR2(100 BYTE), 
	"PERSONESTADO" VARCHAR2(100 BYTE), 
	"PERSONESCOLARIDAD" VARCHAR2(100 BYTE), 
	"PERSONSALARIO" VARCHAR2(100 BYTE), 
	"PERSONSERVICIOSALUD" VARCHAR2(100 BYTE), 
	"PERSONSERVICIOEPS" VARCHAR2(100 BYTE), 
	"PERSONSERVICIOARL" VARCHAR2(100 BYTE), 
	"PERSONSERVICIOTIPOVINCU" VARCHAR2(100 BYTE), 
	"PERSONACTIVIDAD" VARCHAR2(100 BYTE), 
	"PERSONACTIVIDADDURANTENOVEDAD" VARCHAR2(100 BYTE), 
	"PERSONAFP" VARCHAR2(100 BYTE), 
	"PERSONTRABAJOESPECIFICO" VARCHAR2(100 BYTE), 
	"PERSONEXPANO" VARCHAR2(100 BYTE), 
	"PERSONEXPMESES" VARCHAR2(100 BYTE), 
	"PERSONEXPDIAS" VARCHAR2(100 BYTE), 
	"PERSONCAPACITACIONESDES" VARCHAR2(100 BYTE), 
	"DATEULTDESC" VARCHAR2(100 BYTE), 
	"DATEULTREENTRE" VARCHAR2(100 BYTE), 
	"DESHECHOSPRESONAL" VARCHAR2(100 BYTE), 
	"DESDETALLADANOVEDAD" VARCHAR2(100 BYTE), 
	"DESDETALLADAHECHOS" VARCHAR2(100 BYTE), 
	"DESFALLA" VARCHAR2(100 BYTE), 
	"DESCONSECUENCIAS" VARCHAR2(100 BYTE), 
	"DESACT" VARCHAR2(100 BYTE), 
	"CONDIEQUIPODES" VARCHAR2(100 BYTE), 
	"CONDILUGARDES" VARCHAR2(100 BYTE), 
	"CONDIAMBDES" VARCHAR2(100 BYTE), 
	"CONDIORDENPUBLICODES" VARCHAR2(100 BYTE), 
	"CONDIORGDES" VARCHAR2(100 BYTE), 
	"CONDICOMRELACIONDES" VARCHAR2(100 BYTE), 
	"CONDICULTSEGURIDADDES" VARCHAR2(100 BYTE), 
	"CONDILIDERAZGODES" VARCHAR2(100 BYTE), 
	"CONDIPROCEDIMIENTODES" VARCHAR2(100 BYTE), 
	"CONDIRECURSOSDES" VARCHAR2(100 BYTE), 
	"CONDISUPERVISIONDES" VARCHAR2(100 BYTE), 
	"CONDICOMPETENCIADES" VARCHAR2(100 BYTE), 
	"CONDICOGNITIVADES" VARCHAR2(100 BYTE), 
	"CONDIEMOCIONALESDES" VARCHAR2(100 BYTE), 
	"CONDICONOTROSDES" VARCHAR2(100 BYTE), 
	"CONDIFISICASDES" VARCHAR2(100 BYTE), 
	"CONDICOMPORTAMENTALESDES" VARCHAR2(100 BYTE), 
	"CONDITERCEROSDES" VARCHAR2(100 BYTE), 
	"CONDIIDCONTROLDES" VARCHAR2(100 BYTE), 
	"CONDIUSOMATERIALDES" VARCHAR2(100 BYTE), 
	"CONDIMANEJOTRANSPORTEDES" VARCHAR2(100 BYTE), 
	"CONDIEPPKITDES" VARCHAR2(100 BYTE), 
	"CONDIEPPKITDESVEHI" VARCHAR2(100 BYTE), 
	"CONDIPOSTURASDES" VARCHAR2(100 BYTE), 
	"CONDIARMMUNEXPLODES" VARCHAR2(100 BYTE), 
	"CONDICOMPVIADES" VARCHAR2(100 BYTE), 
	"CONDIAUTOINFLINGIDASDES" VARCHAR2(100 BYTE), 
	"VIALTIPOVEHI" VARCHAR2(100 BYTE), 
	"VIALPLACA" VARCHAR2(100 BYTE), 
	"VIALMARCA" VARCHAR2(100 BYTE), 
	"VIALCILINDRAJE" VARCHAR2(100 BYTE), 
	"VIALDEPTRES" VARCHAR2(100 BYTE), 
	"VIALSOAT" VARCHAR2(100 BYTE), 
	"VIALESTADOLICENCIA" VARCHAR2(100 BYTE), 
	"VIALDESDANOS" VARCHAR2(100 BYTE), 
	"VIALCOSTOREP" VARCHAR2(100 BYTE), 
	"VIALSEGTIPOVEHI" VARCHAR2(100 BYTE), 
	"VIALSEGPLACA" VARCHAR2(100 BYTE), 
	"VIALSEGMARCA" VARCHAR2(100 BYTE), 
	"VIALSEGCILINDRAJE" VARCHAR2(100 BYTE), 
	"VIALSEGDEPTRES" VARCHAR2(100 BYTE), 
	"VIALSEGSOAT" VARCHAR2(100 BYTE), 
	"VIALSEGESTADOLICENCIA" VARCHAR2(100 BYTE), 
	"VIALSEGDESDANOS" VARCHAR2(100 BYTE), 
	"VIALSEGCOSTOREP" VARCHAR2(100 BYTE), 
	"DESPERDHUM" VARCHAR2(100 BYTE), 
	"DESPERDAMB" VARCHAR2(100 BYTE), 
	"DESPERDMATER" VARCHAR2(100 BYTE), 
	"DESPERDOTRAS" VARCHAR2(100 BYTE), 
	"DESPERDDIAS" VARCHAR2(100 BYTE), 
	"DESPERDNUMEROMUERTOS" VARCHAR2(100 BYTE), 
	"DESPERDAFECTACION" VARCHAR2(100 BYTE), 
	"DESPERDESTIMACIONVALOR" VARCHAR2(100 BYTE), 
	"DESPERDGENERAL" VARCHAR2(100 BYTE), 
	"ENTREIDUNO" VARCHAR2(100 BYTE), 
	"ENTRECARGOUNO" VARCHAR2(100 BYTE), 
	"ENTRETELUNO" VARCHAR2(100 BYTE), 
	"ENTREDESUNO" VARCHAR2(100 BYTE), 
	"ENTREIDDOS" VARCHAR2(100 BYTE), 
	"ENTRECARGODOS" VARCHAR2(100 BYTE), 
	"ENTRETELDOS" VARCHAR2(100 BYTE), 
	"ENTREDESDOS" VARCHAR2(100 BYTE), 
	"ENTREDESAFECTADO" VARCHAR2(100 BYTE), 
	"REVCUMPLIO" VARCHAR2(100 BYTE), 
	"REVCAUSAS" VARCHAR2(100 BYTE), 
	"REVMEDIDAS" VARCHAR2(100 BYTE), 
	"REGISTROFILENAME1" VARCHAR2(100 BYTE), 
	"REGISTROFILENAME2" VARCHAR2(100 BYTE), 
	"REGISTROFILENAME3" VARCHAR2(100 BYTE), 
	"IMGFIRMAS" VARCHAR2(1000 BYTE), 
	"IDUSER" NUMBER, 
	"DATECREACION" DATE, 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE, 
	"GRUPO_INFORMACION" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FORMS_BASE
--------------------------------------------------------

  CREATE TABLE "SESAT"."FORMS_BASE" 
   (	"ID" NUMBER(11,0), 
	"BASE" NUMBER(11,0), 
	"JSONDATA" VARCHAR2(4000 BYTE), 
	"STATUS" NUMBER(11,0), 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LISTCAT
--------------------------------------------------------

  CREATE TABLE "SESAT"."LISTCAT" 
   (	"ID" NUMBER(11,0), 
	"NAMECAT" VARCHAR2(100 BYTE), 
	"IDENTIFIER" VARCHAR2(200 BYTE), 
	"STATUS" NUMBER(2,0), 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LISTITEM
--------------------------------------------------------

  CREATE TABLE "SESAT"."LISTITEM" 
   (	"ID" NUMBER(11,0), 
	"ID_LISTCAT" NUMBER(11,0), 
	"NAMEITEM" VARCHAR2(200 BYTE), 
	"VALUE" NUMBER(11,0), 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROCESS
--------------------------------------------------------

  CREATE TABLE "SESAT"."PROCESS" 
   (	"ID" NUMBER(11,0), 
	"NAMEPROCESS" VARCHAR2(300 BYTE), 
	"IDUSER" NUMBER(11,0), 
	"FORMATJSON" VARCHAR2(200 BYTE), 
	"LOADPROCESS" NUMBER(11,0), 
	"PERCENTPROCESS" NUMBER(11,0), 
	"IPADDRESS" VARCHAR2(300 BYTE), 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table QUIZ
--------------------------------------------------------

  CREATE TABLE "SESAT"."QUIZ" 
   (	"ID" NUMBER(11,0), 
	"TITLE" VARCHAR2(300 BYTE), 
	"STATUS" NUMBER(2,0), 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERSECURE
--------------------------------------------------------

  CREATE TABLE "SESAT"."USERSECURE" 
   (	"ID" NUMBER(11,0), 
	"MMBUSER" VARCHAR2(50 BYTE), 
	"PASS" VARCHAR2(50 BYTE), 
	"SALT" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"TYPE_DIS" NUMBER(2,0), 
	"STATUS" NUMBER(2,0), 
	"USERROLE" NUMBER(2,0), 
	"ID_P1" NUMBER(11,0), 
	"ID_P2" NUMBER(11,0), 
	"ID_P3" NUMBER(11,0), 
	"USUARIO_CREADOR" VARCHAR2(4000 BYTE), 
	"FECHA_CREACION" DATE, 
	"USUARIO_MODIFICADOR" VARCHAR2(4000 BYTE), 
	"FECHA_MODIFICACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Sequence SEQ_FORMINVESTIGACION
--------------------------------------------------------

   CREATE SEQUENCE  "SESAT"."SEQ_FORMINVESTIGACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LISTCAT
--------------------------------------------------------

   CREATE SEQUENCE  "SESAT"."SEQ_LISTCAT"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_LISTITEM
--------------------------------------------------------

   CREATE SEQUENCE  "SESAT"."SEQ_LISTITEM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE ;
REM INSERTING into SESAT.ELEMPRESTADOS
SET DEFINE OFF;
Insert into SESAT.ELEMPRESTADOS (USERID,ELEM,DATEIN,OBS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION,GRUPO_INFORMACION,ID) values ('1','2',to_date('05/06/18','DD/MM/RR'),'CCC','1',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'),'1','1');
REM INSERTING into SESAT.FORMACCIONINVESTIGACION
SET DEFINE OFF;
Insert into SESAT.FORMACCIONINVESTIGACION (ID,IDFORM,TYPETIME,PLANACCIONPREV,PLANACCIONRES,PLANACCIONDATEEXE,PLANACCIONRECURSOS,PLANACCIONRESCUMPLIR,PLANACCIONDATECLOSE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION,GRUPO_INFORMACION) values ('1','eeso','d',to_date('05/06/18','DD/MM/RR'),'ss',to_date('05/06/18','DD/MM/RR'),'ssss','ssss',to_date('05/06/18','DD/MM/RR'),'ssss',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'),'1');
Insert into SESAT.FORMACCIONINVESTIGACION (ID,IDFORM,TYPETIME,PLANACCIONPREV,PLANACCIONRES,PLANACCIONDATEEXE,PLANACCIONRECURSOS,PLANACCIONRESCUMPLIR,PLANACCIONDATECLOSE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION,GRUPO_INFORMACION) values ('2','1','ESCOM',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'),'ESCOM','ddd',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'),'ESCOM',to_date('05/06/18','DD/MM/RR'),null);
Insert into SESAT.FORMACCIONINVESTIGACION (ID,IDFORM,TYPETIME,PLANACCIONPREV,PLANACCIONRES,PLANACCIONDATEEXE,PLANACCIONRECURSOS,PLANACCIONRESCUMPLIR,PLANACCIONDATECLOSE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION,GRUPO_INFORMACION) values ('3','1','ESCOM',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'),'ESCOM','ddd',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'),'ESCOM',to_date('05/06/18','DD/MM/RR'),'2');
REM INSERTING into SESAT.FORMINVESTIGACION
SET DEFINE OFF;
Insert into SESAT.FORMINVESTIGACION (ID,PREINFORME,PERCENT,NITINS,NITCON,JEFAESTMAYOR,UNITAC,DIVCOMAN,FUERZATAREA,BRIGADADIRECCION,CEDE,DATENOVEDAD,HORANOVEDAD,MINNOVEDAD,DATEANALISIS,ZONANOVEDAD,COORDIRECCION,PAISNOVEDAD,DEPNOVEDAD,CIUDADNOVEDAD,CARACLUGAR,SITIOESPECIFICO,CLASENOVEDAD,NOVEDADINTERNAFUERZA,NOVEDADINTERNAFUERZASUB,GRAVEDAD,PARTECUERPO,PARTECUERPODES,ATENCIONINMEDIATA,INFOGRADO,INFOCARGO,INFONAME,INFOEXTRELACION,INFOEXTNAME,FUENTEAGENTE,AGENTE,OTROAGENTE,MECALESION,NOMBREREPORTA,GRADOREPORTA,CARGOREPORTA,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,PERSOGRADO,PERSOCARGO,ARMACUERPOESP,PERSODOC,DATEPERSONNAC,LUGARPERSONNAC,DATEPERSONINGRE,PERSONCONTINGENTE,TIMEPOSERVICIOANOS,TIMEPOSERVICIOMESES,TIMEPOSERVICIOANOSUNIDAD,TIMEPOSERVICIOMESESUNIDAD,HORASLABORADO,MINLABORADO,TIMEPOSERVICIOANOSCARGO,TIMEPOSERVICIOMESESCARGO,PERSONDIRECCION,PERSONCIUDAD,PERSONTEL,PERSONEDAD,PERSONSEXO,PERSONESTADO,PERSONESCOLARIDAD,PERSONSALARIO,PERSONSERVICIOSALUD,PERSONSERVICIOEPS,PERSONSERVICIOARL,PERSONSERVICIOTIPOVINCU,PERSONACTIVIDAD,PERSONACTIVIDADDURANTENOVEDAD,PERSONAFP,PERSONTRABAJOESPECIFICO,PERSONEXPANO,PERSONEXPMESES,PERSONEXPDIAS,PERSONCAPACITACIONESDES,DATEULTDESC,DATEULTREENTRE,DESHECHOSPRESONAL,DESDETALLADANOVEDAD,DESDETALLADAHECHOS,DESFALLA,DESCONSECUENCIAS,DESACT,CONDIEQUIPODES,CONDILUGARDES,CONDIAMBDES,CONDIORDENPUBLICODES,CONDIORGDES,CONDICOMRELACIONDES,CONDICULTSEGURIDADDES,CONDILIDERAZGODES,CONDIPROCEDIMIENTODES,CONDIRECURSOSDES,CONDISUPERVISIONDES,CONDICOMPETENCIADES,CONDICOGNITIVADES,CONDIEMOCIONALESDES,CONDICONOTROSDES,CONDIFISICASDES,CONDICOMPORTAMENTALESDES,CONDITERCEROSDES,CONDIIDCONTROLDES,CONDIUSOMATERIALDES,CONDIMANEJOTRANSPORTEDES,CONDIEPPKITDES,CONDIEPPKITDESVEHI,CONDIPOSTURASDES,CONDIARMMUNEXPLODES,CONDICOMPVIADES,CONDIAUTOINFLINGIDASDES,VIALTIPOVEHI,VIALPLACA,VIALMARCA,VIALCILINDRAJE,VIALDEPTRES,VIALSOAT,VIALESTADOLICENCIA,VIALDESDANOS,VIALCOSTOREP,VIALSEGTIPOVEHI,VIALSEGPLACA,VIALSEGMARCA,VIALSEGCILINDRAJE,VIALSEGDEPTRES,VIALSEGSOAT,VIALSEGESTADOLICENCIA,VIALSEGDESDANOS,VIALSEGCOSTOREP,DESPERDHUM,DESPERDAMB,DESPERDMATER,DESPERDOTRAS,DESPERDDIAS,DESPERDNUMEROMUERTOS,DESPERDAFECTACION,DESPERDESTIMACIONVALOR,DESPERDGENERAL,ENTREIDUNO,ENTRECARGOUNO,ENTRETELUNO,ENTREDESUNO,ENTREIDDOS,ENTRECARGODOS,ENTRETELDOS,ENTREDESDOS,ENTREDESAFECTADO,REVCUMPLIO,REVCAUSAS,REVMEDIDAS,REGISTROFILENAME1,REGISTROFILENAME2,REGISTROFILENAME3,IMGFIRMAS,IDUSER,DATECREACION,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION,GRUPO_INFORMACION) values ('1','dddd','10','dds','sss','ssss','ssss','sss','ddd','sss','6',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SESAT.FORMINVESTIGACION (ID,PREINFORME,PERCENT,NITINS,NITCON,JEFAESTMAYOR,UNITAC,DIVCOMAN,FUERZATAREA,BRIGADADIRECCION,CEDE,DATENOVEDAD,HORANOVEDAD,MINNOVEDAD,DATEANALISIS,ZONANOVEDAD,COORDIRECCION,PAISNOVEDAD,DEPNOVEDAD,CIUDADNOVEDAD,CARACLUGAR,SITIOESPECIFICO,CLASENOVEDAD,NOVEDADINTERNAFUERZA,NOVEDADINTERNAFUERZASUB,GRAVEDAD,PARTECUERPO,PARTECUERPODES,ATENCIONINMEDIATA,INFOGRADO,INFOCARGO,INFONAME,INFOEXTRELACION,INFOEXTNAME,FUENTEAGENTE,AGENTE,OTROAGENTE,MECALESION,NOMBREREPORTA,GRADOREPORTA,CARGOREPORTA,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,PERSOGRADO,PERSOCARGO,ARMACUERPOESP,PERSODOC,DATEPERSONNAC,LUGARPERSONNAC,DATEPERSONINGRE,PERSONCONTINGENTE,TIMEPOSERVICIOANOS,TIMEPOSERVICIOMESES,TIMEPOSERVICIOANOSUNIDAD,TIMEPOSERVICIOMESESUNIDAD,HORASLABORADO,MINLABORADO,TIMEPOSERVICIOANOSCARGO,TIMEPOSERVICIOMESESCARGO,PERSONDIRECCION,PERSONCIUDAD,PERSONTEL,PERSONEDAD,PERSONSEXO,PERSONESTADO,PERSONESCOLARIDAD,PERSONSALARIO,PERSONSERVICIOSALUD,PERSONSERVICIOEPS,PERSONSERVICIOARL,PERSONSERVICIOTIPOVINCU,PERSONACTIVIDAD,PERSONACTIVIDADDURANTENOVEDAD,PERSONAFP,PERSONTRABAJOESPECIFICO,PERSONEXPANO,PERSONEXPMESES,PERSONEXPDIAS,PERSONCAPACITACIONESDES,DATEULTDESC,DATEULTREENTRE,DESHECHOSPRESONAL,DESDETALLADANOVEDAD,DESDETALLADAHECHOS,DESFALLA,DESCONSECUENCIAS,DESACT,CONDIEQUIPODES,CONDILUGARDES,CONDIAMBDES,CONDIORDENPUBLICODES,CONDIORGDES,CONDICOMRELACIONDES,CONDICULTSEGURIDADDES,CONDILIDERAZGODES,CONDIPROCEDIMIENTODES,CONDIRECURSOSDES,CONDISUPERVISIONDES,CONDICOMPETENCIADES,CONDICOGNITIVADES,CONDIEMOCIONALESDES,CONDICONOTROSDES,CONDIFISICASDES,CONDICOMPORTAMENTALESDES,CONDITERCEROSDES,CONDIIDCONTROLDES,CONDIUSOMATERIALDES,CONDIMANEJOTRANSPORTEDES,CONDIEPPKITDES,CONDIEPPKITDESVEHI,CONDIPOSTURASDES,CONDIARMMUNEXPLODES,CONDICOMPVIADES,CONDIAUTOINFLINGIDASDES,VIALTIPOVEHI,VIALPLACA,VIALMARCA,VIALCILINDRAJE,VIALDEPTRES,VIALSOAT,VIALESTADOLICENCIA,VIALDESDANOS,VIALCOSTOREP,VIALSEGTIPOVEHI,VIALSEGPLACA,VIALSEGMARCA,VIALSEGCILINDRAJE,VIALSEGDEPTRES,VIALSEGSOAT,VIALSEGESTADOLICENCIA,VIALSEGDESDANOS,VIALSEGCOSTOREP,DESPERDHUM,DESPERDAMB,DESPERDMATER,DESPERDOTRAS,DESPERDDIAS,DESPERDNUMEROMUERTOS,DESPERDAFECTACION,DESPERDESTIMACIONVALOR,DESPERDGENERAL,ENTREIDUNO,ENTRECARGOUNO,ENTRETELUNO,ENTREDESUNO,ENTREIDDOS,ENTRECARGODOS,ENTRETELDOS,ENTREDESDOS,ENTREDESAFECTADO,REVCUMPLIO,REVCAUSAS,REVMEDIDAS,REGISTROFILENAME1,REGISTROFILENAME2,REGISTROFILENAME3,IMGFIRMAS,IDUSER,DATECREACION,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION,GRUPO_INFORMACION) values ('2','info','10','hdhdhd','otro','JEMPP','Dipic','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
Insert into SESAT.FORMINVESTIGACION (ID,PREINFORME,PERCENT,NITINS,NITCON,JEFAESTMAYOR,UNITAC,DIVCOMAN,FUERZATAREA,BRIGADADIRECCION,CEDE,DATENOVEDAD,HORANOVEDAD,MINNOVEDAD,DATEANALISIS,ZONANOVEDAD,COORDIRECCION,PAISNOVEDAD,DEPNOVEDAD,CIUDADNOVEDAD,CARACLUGAR,SITIOESPECIFICO,CLASENOVEDAD,NOVEDADINTERNAFUERZA,NOVEDADINTERNAFUERZASUB,GRAVEDAD,PARTECUERPO,PARTECUERPODES,ATENCIONINMEDIATA,INFOGRADO,INFOCARGO,INFONAME,INFOEXTRELACION,INFOEXTNAME,FUENTEAGENTE,AGENTE,OTROAGENTE,MECALESION,NOMBREREPORTA,GRADOREPORTA,CARGOREPORTA,PNOMBRE,SNOMBRE,PAPELLIDO,SAPELLIDO,PERSOGRADO,PERSOCARGO,ARMACUERPOESP,PERSODOC,DATEPERSONNAC,LUGARPERSONNAC,DATEPERSONINGRE,PERSONCONTINGENTE,TIMEPOSERVICIOANOS,TIMEPOSERVICIOMESES,TIMEPOSERVICIOANOSUNIDAD,TIMEPOSERVICIOMESESUNIDAD,HORASLABORADO,MINLABORADO,TIMEPOSERVICIOANOSCARGO,TIMEPOSERVICIOMESESCARGO,PERSONDIRECCION,PERSONCIUDAD,PERSONTEL,PERSONEDAD,PERSONSEXO,PERSONESTADO,PERSONESCOLARIDAD,PERSONSALARIO,PERSONSERVICIOSALUD,PERSONSERVICIOEPS,PERSONSERVICIOARL,PERSONSERVICIOTIPOVINCU,PERSONACTIVIDAD,PERSONACTIVIDADDURANTENOVEDAD,PERSONAFP,PERSONTRABAJOESPECIFICO,PERSONEXPANO,PERSONEXPMESES,PERSONEXPDIAS,PERSONCAPACITACIONESDES,DATEULTDESC,DATEULTREENTRE,DESHECHOSPRESONAL,DESDETALLADANOVEDAD,DESDETALLADAHECHOS,DESFALLA,DESCONSECUENCIAS,DESACT,CONDIEQUIPODES,CONDILUGARDES,CONDIAMBDES,CONDIORDENPUBLICODES,CONDIORGDES,CONDICOMRELACIONDES,CONDICULTSEGURIDADDES,CONDILIDERAZGODES,CONDIPROCEDIMIENTODES,CONDIRECURSOSDES,CONDISUPERVISIONDES,CONDICOMPETENCIADES,CONDICOGNITIVADES,CONDIEMOCIONALESDES,CONDICONOTROSDES,CONDIFISICASDES,CONDICOMPORTAMENTALESDES,CONDITERCEROSDES,CONDIIDCONTROLDES,CONDIUSOMATERIALDES,CONDIMANEJOTRANSPORTEDES,CONDIEPPKITDES,CONDIEPPKITDESVEHI,CONDIPOSTURASDES,CONDIARMMUNEXPLODES,CONDICOMPVIADES,CONDIAUTOINFLINGIDASDES,VIALTIPOVEHI,VIALPLACA,VIALMARCA,VIALCILINDRAJE,VIALDEPTRES,VIALSOAT,VIALESTADOLICENCIA,VIALDESDANOS,VIALCOSTOREP,VIALSEGTIPOVEHI,VIALSEGPLACA,VIALSEGMARCA,VIALSEGCILINDRAJE,VIALSEGDEPTRES,VIALSEGSOAT,VIALSEGESTADOLICENCIA,VIALSEGDESDANOS,VIALSEGCOSTOREP,DESPERDHUM,DESPERDAMB,DESPERDMATER,DESPERDOTRAS,DESPERDDIAS,DESPERDNUMEROMUERTOS,DESPERDAFECTACION,DESPERDESTIMACIONVALOR,DESPERDGENERAL,ENTREIDUNO,ENTRECARGOUNO,ENTRETELUNO,ENTREDESUNO,ENTREIDDOS,ENTRECARGODOS,ENTRETELDOS,ENTREDESDOS,ENTREDESAFECTADO,REVCUMPLIO,REVCAUSAS,REVMEDIDAS,REGISTROFILENAME1,REGISTROFILENAME2,REGISTROFILENAME3,IMGFIRMAS,IDUSER,DATECREACION,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION,GRUPO_INFORMACION) values ('3','info','10','hdhdhd','otro','JEMOP','DipOC','1',null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);
REM INSERTING into SESAT.FORMS_BASE
SET DEFINE OFF;
Insert into SESAT.FORMS_BASE (ID,BASE,JSONDATA,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('1','1','Json','1','1',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'));
Insert into SESAT.FORMS_BASE (ID,BASE,JSONDATA,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('2','1','base','1','1',to_date('06/06/18','DD/MM/RR'),'1',to_date('06/06/18','DD/MM/RR'));
REM INSERTING into SESAT.LISTCAT
SET DEFINE OFF;
Insert into SESAT.LISTCAT (ID,NAMECAT,IDENTIFIER,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('1','Jefatura de Estado Mayor','jefaEstMayor','1','1',to_date('22/05/18','DD/MM/RR'),'1',to_date('22/05/18','DD/MM/RR'));
Insert into SESAT.LISTCAT (ID,NAMECAT,IDENTIFIER,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('3','Division o Comando','divcoman','1','1',to_date('24/05/18','DD/MM/RR'),'1',to_date('24/05/18','DD/MM/RR'));
Insert into SESAT.LISTCAT (ID,NAMECAT,IDENTIFIER,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('21','CEDE','CD','1','1',to_date('27/05/18','DD/MM/RR'),'1',to_date('27/05/18','DD/MM/RR'));
Insert into SESAT.LISTCAT (ID,NAMECAT,IDENTIFIER,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('5','Unidad Tactica','uniTac','2','2',to_date('24/05/18','DD/MM/RR'),'2',to_date('24/05/18','DD/MM/RR'));
Insert into SESAT.LISTCAT (ID,NAMECAT,IDENTIFIER,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('22','FUERZA DE TAREA','FT','1','1',to_date('27/05/18','DD/MM/RR'),'1',to_date('27/05/18','DD/MM/RR'));
Insert into SESAT.LISTCAT (ID,NAMECAT,IDENTIFIER,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('41','JEFATURA DE ESTADO MAYOR','JEFAESTMAYOR','1','1',to_date('22/05/18','DD/MM/RR'),'1',to_date('22/05/18','DD/MM/RR'));
Insert into SESAT.LISTCAT (ID,NAMECAT,IDENTIFIER,STATUS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('42','BRIGADA','BR','1','1',to_date('28/05/18','DD/MM/RR'),'1',to_date('28/05/18','DD/MM/RR'));
REM INSERTING into SESAT.LISTITEM
SET DEFINE OFF;
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('2','1','CEDE4','1','1',to_date('23/05/18','DD/MM/RR'),'1',to_date('23/05/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('1','1','SECEJ','0','1',to_date('23/05/18','DD/MM/RR'),'1',to_date('23/05/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('6','1','JEMPP','0','1',to_date('26/05/18','DD/MM/RR'),'1',to_date('26/05/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('7','1','JEMOP','0','1',to_date('26/05/18','DD/MM/RR'),'1',to_date('26/05/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('21','1','CGFM','1','1',to_date('27/05/18','DD/MM/RR'),'1',to_date('28/05/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('22','1','BRCOM','0','1',to_date('28/05/18','DD/MM/RR'),'1',to_date('28/05/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('23','1','BRCOM','1','1',to_date('28/05/18','DD/MM/RR'),'1',to_date('28/05/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('41','1','BRCOM','1','1',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('42','1','ESCOM','1','1',to_date('05/06/18','DD/MM/RR'),'1',to_date('05/06/18','DD/MM/RR'));
Insert into SESAT.LISTITEM (ID,ID_LISTCAT,NAMEITEM,VALUE,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('43','0','ESINT','0','0',to_date('05/06/18','DD/MM/RR'),'0',to_date('05/06/18','DD/MM/RR'));
REM INSERTING into SESAT.PROCESS
SET DEFINE OFF;
Insert into SESAT.PROCESS (ID,NAMEPROCESS,IDUSER,FORMATJSON,LOADPROCESS,PERCENTPROCESS,IPADDRESS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('1','ddd','1','sdasssserrb gfgfgfgf','1','5','1','1',to_date('06/06/18','DD/MM/RR'),'1',to_date('06/06/18','DD/MM/RR'));
Insert into SESAT.PROCESS (ID,NAMEPROCESS,IDUSER,FORMATJSON,LOADPROCESS,PERCENTPROCESS,IPADDRESS,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('2','Nombre','1','Json2','1','10','10.23.2.54','1',to_date('06/06/18','DD/MM/RR'),'1',to_date('06/06/18','DD/MM/RR'));
REM INSERTING into SESAT.QUIZ
SET DEFINE OFF;
REM INSERTING into SESAT.USERSECURE
SET DEFINE OFF;
Insert into SESAT.USERSECURE (ID,MMBUSER,PASS,SALT,NAME,TYPE_DIS,STATUS,USERROLE,ID_P1,ID_P2,ID_P3,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('1','nombre','sss','sdsd','ddddd','1','1','1','1','1','1','1',to_date('06/06/18','DD/MM/RR'),'1',to_date('06/06/18','DD/MM/RR'));
Insert into SESAT.USERSECURE (ID,MMBUSER,PASS,SALT,NAME,TYPE_DIS,STATUS,USERROLE,ID_P1,ID_P2,ID_P3,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('2','Nombre','babab','sal','nombre','1','1','1','1','1','1','1',to_date('06/06/18','DD/MM/RR'),'1',to_date('06/06/18','DD/MM/RR'));
Insert into SESAT.USERSECURE (ID,MMBUSER,PASS,SALT,NAME,TYPE_DIS,STATUS,USERROLE,ID_P1,ID_P2,ID_P3,USUARIO_CREADOR,FECHA_CREACION,USUARIO_MODIFICADOR,FECHA_MODIFICACION) values ('3','Nombre','babab','sal','Ejemplo','1','1','1','1','2','2','1',to_date('06/06/18','DD/MM/RR'),'1',to_date('06/06/18','DD/MM/RR'));
--------------------------------------------------------
--  DDL for Index ID_LISTCAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESAT"."ID_LISTCAT_PK" ON "SESAT"."LISTCAT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_FORMINVESTIGACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESAT"."ID_FORMINVESTIGACION_PK" ON "SESAT"."FORMINVESTIGACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_FORMACCIONINVESTIGACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESAT"."ID_FORMACCIONINVESTIGACION_PK" ON "SESAT"."FORMACCIONINVESTIGACION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_FORMS_BASE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESAT"."ID_FORMS_BASE_PK" ON "SESAT"."FORMS_BASE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_USERSECURE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESAT"."ID_USERSECURE_PK" ON "SESAT"."USERSECURE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_QUIZ_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESAT"."ID_QUIZ_PK" ON "SESAT"."QUIZ" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_LISTITEM_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESAT"."ID_LISTITEM_PK" ON "SESAT"."LISTITEM" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ID_ELEMPRESTADOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SESAT"."ID_ELEMPRESTADOS_PK" ON "SESAT"."ELEMPRESTADOS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger T_LISTCAT
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SESAT"."T_LISTCAT" 
  before insert on "LISTCAT"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "SEQ_LISTCAT".nextval into :NEW."ID" from dual; 
  end if; 
end;
/
ALTER TRIGGER "SESAT"."T_LISTCAT" ENABLE;
--------------------------------------------------------
--  DDL for Trigger T_LISTITEM
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "SESAT"."T_LISTITEM" 
  before insert on "LISTITEM"               
  for each row  
begin   
  if :NEW."ID" is null then 
    select "SEQ_LISTITEM".nextval into :NEW."ID" from dual; 
  end if; 
end;
/
ALTER TRIGGER "SESAT"."T_LISTITEM" ENABLE;
--------------------------------------------------------
--  Constraints for Table LISTITEM
--------------------------------------------------------

  ALTER TABLE "SESAT"."LISTITEM" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."LISTITEM" ADD CONSTRAINT "ID_LISTITEM_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMACCIONINVESTIGACION
--------------------------------------------------------

  ALTER TABLE "SESAT"."FORMACCIONINVESTIGACION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."FORMACCIONINVESTIGACION" ADD CONSTRAINT "ID_FORMACCIONINVESTIGACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LISTCAT
--------------------------------------------------------

  ALTER TABLE "SESAT"."LISTCAT" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."LISTCAT" ADD CONSTRAINT "ID_LISTCAT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 81920 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ELEMPRESTADOS
--------------------------------------------------------

  ALTER TABLE "SESAT"."ELEMPRESTADOS" MODIFY ("USERID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."ELEMPRESTADOS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."ELEMPRESTADOS" ADD CONSTRAINT "ID_ELEMPRESTADOS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FORMS_BASE
--------------------------------------------------------

  ALTER TABLE "SESAT"."FORMS_BASE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."FORMS_BASE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."FORMS_BASE" MODIFY ("JSONDATA" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."FORMS_BASE" ADD CONSTRAINT "ID_FORMS_BASE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERSECURE
--------------------------------------------------------

  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("ID_P3" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("ID_P2" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("ID_P1" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("USERROLE" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("TYPE_DIS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("SALT" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("PASS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("MMBUSER" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."USERSECURE" ADD CONSTRAINT "ID_USERSECURE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table QUIZ
--------------------------------------------------------

  ALTER TABLE "SESAT"."QUIZ" MODIFY ("STATUS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."QUIZ" MODIFY ("TITLE" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."QUIZ" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."QUIZ" ADD CONSTRAINT "ID_QUIZ_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROCESS
--------------------------------------------------------

  ALTER TABLE "SESAT"."PROCESS" MODIFY ("IPADDRESS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."PROCESS" MODIFY ("PERCENTPROCESS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."PROCESS" MODIFY ("LOADPROCESS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."PROCESS" MODIFY ("FORMATJSON" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."PROCESS" MODIFY ("IDUSER" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."PROCESS" MODIFY ("NAMEPROCESS" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."PROCESS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FORMINVESTIGACION
--------------------------------------------------------

  ALTER TABLE "SESAT"."FORMINVESTIGACION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SESAT"."FORMINVESTIGACION" ADD CONSTRAINT "ID_FORMINVESTIGACION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
